### ISSUE TITLE
Support for connecting through proxy

### ISSUE THREAD

**Issue by leon-vg** [phonegap-build/pgb-api#4]
It would be really nice if this plugin would support connecting through a proxy. 

I tried using the pgb-cli (that uses the pgb-api underwater), but found out that this is not possible if behind a corporate proxy.

My proposal would be to use the 'request' module instead of http.request and https.request, because that module respects the HTTP_PROXY and HTTPS_PROXY environment variables. Therefore, this module would work with a proxy without the need to set this explicitly for this module.

**Comment by goya** [comment]
what proxy do you use?  it over https or http?

**Comment by leon-vg** [comment]
The proxy itself is a http proxy. Both https and http traffic are routed over this proxy. Also, the proxy is unauthenticated. It is in the form of http://proxy.company.local:8080.
