### ISSUE TITLE
buildApp command never triggers a build

### ISSUE THREAD

**Issue by nickbeckenham** [phonegap-build/pgb-api#5]
I am implementing this api into my build process and I have noticed that the app will only ever trigger a build on phonegap build if I modify the config.xml such as put in a new version or change the description etc.

As we trigger a build every time we check in code, the version number doesn't necessarily change on every check in, so the config.xml doesn't change either. So even though we upload a new .zip file with new code changes in it, the build doesn't get triggered automatically, and when I try to call buildApp directly to trigger the build, it still returns immediately with 'completed' and never 'pending' and never actually builds the app

**Comment by goya** [comment]
is hydration on?

**Comment by nickbeckenham** [comment]
@goya Yes it is, will that affect the build?

**Comment by goya** [comment]
well it doesnt build unless the config.xml changes.  the installed app will just refresh on the device.

**Comment by nickbeckenham** [comment]
ah okay, I believe that solves my problem, though I'm still surprised that the 'buildApp' function doesn't behave the same way as say clicking 'rebuild all' on build.phonegap.com does. But if that's the intent of the API that's fine.
